#define TOOLCHAIN_VERSION "#63 mardi 8 janvier 2013, 19:59:30 (UTC+0100)"
#define TOOLCHAIN_COMPILE_TIME "19:59:30"
#define TOOLCHAIN_COMPILE_BY "geoffrey"
#define TOOLCHAIN_COMPILE_HOST "geoffrey-box"
#define TOOLCHAIN_COMPILE_DOMAIN ""
#define TOOLCHAIN_COMPILER "gcc version 3.4.4"
