#
# Makefile for the linux kernel.
#

# Object file lists.

obj-y		:= arch.o irq.o time.o
obj-m		:=
obj-n		:=
obj-		:=

#extra-y	:= head.o

# CPU-specific support
obj-$(CONFIG_CPU_LPC2468) += lpc2468_devices.o
